### ISSUE TITLE
pdflatex fails on fragile frame if \end{frame} is preceded by whitespace on its line

### ISSUE THREAD

**Issue by josephwright** [josephwright/beamer#326]
Originally reported by: **Johannes Rauh (Bitbucket: [jarauh](https://bitbucket.org/jarauh), GitHub: Unknown)**

----------------------------------------

The following program fails (also attached):
```
#!latex

\documentclass{beamer}
\begin{document}
\begin{frame}[fragile]

 \end{frame}
\end{document}
```

Note the space in the second-last row: " \end{frame}".  The manual beameruserguide.pdf states: "(...)  the \end{frame} must be alone on a single line."  So either this is a bug that can be solved, or it should be mentioned in the manual.

I'm using beamer 3.33 with pdfTeX, Version 3.14159265-2.6-1.40.15 (TeX Live 2015/dev/Debian).

----------------------------------------
- Bitbucket: https://bitbucket.org/rivanvx/beamer/issue/326

**Comment by ghost** [comment]
A few related questions:

http://tex.stackexchange.com/questions/17827/beamer-error-driving-me-nuts
http://tex.stackexchange.com/questions/277842/error-when-using-fragile-in-beamer
http://tex.stackexchange.com/questions/225581/beamer-file-ended-while-scanning-use-of-next
http://tex.stackexchange.com/questions/234778/indenting-endframe-in-fragile-slides
http://tex.stackexchange.com/questions/246147/file-ended-while-scanning-use-of-next

**Comment by josephwright** [comment]
Yes, I know about this: I'm not sure there's a good solution other than documentation! I will take a look (I'm having a review of `beamer` bugs).

**Comment by ghost** [comment]
I may be biased, because I personally don't really like this "new" behaviour of beamer, but maybe it would be a solution to add some option to switch this off or on?

As far as I understood, this is a trade-off between allowing tabs in listings and allowing the `\end{frame}` to be indented. I would even go as far and have the "allowing the `\end{frame}` to be indented" as default behaviour and make "allowing tabs in listings" as optional for the following reasons:

- Besides the explicit questions I linked above, there were many cases on TeX.SE where this caused problems, especially because the resulting error message is not really obvious for the majority of users. For me, such discussions manly occurred in comments, so not really easy to search for with the on-site search function, but I can dig for a few of these discussions, if this would be helpful. One example http://tex.stackexchange.com/questions/325468/errors-when-incorporating-a-plot-into-a-beamer-document/325472#comment795454_325472

- I can not give any representative numbers,  but I feel as if the number of fragile frames used together with tabs in listings may not be the majority of use-cases as a) not every listings uses tabs and b) not every fragile frame has a listing - there are many cases where it is simply used for something tikz related or similar

- No representative numbers for this either, but based on my experience on TeX.SE, a significant number of users indents their frames.

Con: this makes it easy to get rep points on TeX.SE once one knows the error message :)

**Comment by josephwright** [comment]
@samcarter8 I'll take another look at this and see if I can find a technical solution. What I note here is that if I don't allow for tabs in the core code then users have no easy approach, whereas if I say 'no indenting `\end{frame}` for fragile frames' then they can format their so things work. I do agree the error message is unhelpful!

**Comment by josephwright** [comment]
For tab business, see https://github.com/josephwright/beamer/issues/310

**Comment by josephwright** [comment]
See http://tex.stackexchange.com/questions/343717/why-cant-beamer-skip-white-spaces-when-looking-for-endframe-in-a-fragile-fra/34372 for discussion and at least one solution: just a question of what to go with,
