### ISSUE TITLE
Margin incorrect for quotes inside lists

### ISSUE THREAD

**Issue by josephwright** [josephwright/beamer#352]
From a mail from @frankmittelbach:
```latex
\documentclass{beamer}

\begin{document}

\begin{frame}{}
  \begin{proof}
    \begin{enumerate}
    \item now a quote
      \begin{quote}
        This comes out as 3 level why? As far as I can see at least.
      \end{quote}
    \item x
      \begin{enumerate}
      \item x
        \begin{enumerate}
        \item x
        \item
        \end{enumerate}
      \item
      \end{enumerate}
    \item now a quote
      \begin{quote}
        This comes out as 3 level why?
      \end{quote}
    \item
    \item
    \end{enumerate}
  \end{proof}
\end{frame}

\stop 
```
As Frank says, this can be fixed by adding 
```latex
\makeatletter
\addtobeamertemplate{quotation begin}{}{\@totalleftmargin\z@}
\addtobeamertemplate{quote begin}{}{\@totalleftmargin\z@}
\makeatother 
```
but probably `beamercolorbox` should do this or perhaps `\@arrayparboxrestore`. The question is the knock-on effect on spacing 'in the wild.

**Comment by FrankMittelbach** [comment]
> As Frank says, this can be fixed by adding
>
> \makeatletter
> \addtobeamertemplate{quotation begin}{}{\@totalleftmargin\z@}
> \addtobeamertemplate{quote begin}{}{\@totalleftmargin\z@}
> \makeatother
>
> but probably |beamercolorbox| should do this or perhaps
> |\@arrayparboxrestore|. The question is the knock-on effect on spacing
> 'in the wild.

I meant maybe the \beamercolorbox needs to call \«arrayboxrestore (that 
one does reset \@totalleftmargin plus some other things)

it is a glaring bug (and I'm a bit surprised that nobody reported it 
earlier as I guess it is there fore a very long time).

Basically it means a "background color layer" (that often is even 
invisible) results in applying a left margin indent twice, thereby 
getting the visual alignment totally out of sync.

The logic of the list env code expects that everything  nested list is 
positioned according to the outer left margin and if you throw in a vbox 
then you are suddenly position against the vbox boundary but with values 
calculated for the outer margin. Position against that box is correct if 
you are setting up a new visual context (like in a minipage) but here 
all that the box is for is doing some background coloring

The problem is that I don't know if there is other \beamercolorbox usage 
that would conflict with this view of the world (meaning you may need 
two commands) but it should really go into the \beamercolorbox command 
if its use in such places is an advocated use (or the advocated use) the 
above change to the template is only to keep my presentation going

As for in the wild: a fix like this would mean that elements based on 
trivlist would get their leftmargin reduced thus they have more space 
horizontally available. That will change slides but what happens now is 
so wrong so ...

**Comment by FrankMittelbach** [comment]
A related bit of weirdness that needs thinking about

   \begin{frame}{}
  \begin{enumerate}
    \item bla bla
      \begin{block}{XXXX}
        Block text is flush left but
      \begin{quote}
        but the quote jumps back to 2 level indentation
      \end{quote}
        \begin{itemize}
        \item and so does another list
        \end{itemize}
        That's too a little weird. perhaps the block should indent
        with the list? Or at least the body text
      \end{block}
       and more text

**Comment by josephwright** [comment]
On 05/01/2017 12:09, Frank Mittelbach wrote:
> I meant maybe the `\beamercolorbox` needs to call `\@arrayboxrestore` (that 
> one does reset `\@totalleftmargin` plus some other things)

Yes, understood.

> it is a glaring bug (and I'm a bit surprised that nobody reported it 
> earlier as I guess it is there fore a very long time).

Ah, there are various 'interesting' spacing issues in `beamer` and it's quite possible no-one has followed this one through. More generally, `beamer` usage tends toward simply (non-nested) lists or directly placement of text/graphics on a page, with at least some element of visual adjustment required. So it's a place where some spacing oddities are likely to be overlooked.

> The logic of the list env code expects that everything  nested list is 
> positioned according to the outer left margin and if you throw in a vbox 
> then you are suddenly position against the vbox boundary but with values 
> calculated for the outer margin. Position against that box is correct if 
> you are setting up a new visual context (like in a minipage) but here 
> all that the box is for is doing some background coloring

Indeed.

> The problem is that I don't know if there is other `\beamercolorbox` usage 
> that would conflict with this view of the world (meaning you may need 
> two commands) but it should really go into the `\beamercolorbox` command 
> if its use in such places is an advocated use (or the advocated use) the 
> above change to the template is only to keep my presentation going

The entire point of these boxes is to add background colour; that's clear from the manual (Till's text, not mine or Vedran's).

> As for in the wild: a fix like this would mean that elements based on 
> trivlist would get their leftmargin reduced thus they have more space 
> horizontally available. That will change slides but what happens now is 
> so wrong so ...

I'll probably just add it and see what happens: tends to be the way things have worked to-date!

**Comment by josephwright** [comment]
On 05/01/2017 12:32, Frank Mittelbach wrote:
> A related bit of weirdness that needs thinking about
> 
>    \begin{frame}{}
>   \begin{enumerate}
>     \item bla bla
>       \begin{block}{XXXX}
>         Block text is flush left but
>       \begin{quote}
>         but the quote jumps back to 2 level indentation
>       \end{quote}
>         \begin{itemize}
>         \item and so does another list
>         \end{itemize}
>         That's too a little weird. perhaps the block should indent
>         with the list? Or at least the body text
>       \end{block}
>        and more text

I'll open another issue for this (I'm trying to be more organised with the issue tracking this year).

**Comment by louisstuart96** [comment]
Seems like `\actionenv` command typesets `quote` environment incorrectly in a horizontal list, like this MWE below:

```
\documentclass{beamer}

\begin{document}

\begin{frame}{}
  1\begin{enumerate}
    \item Test list.
    \item Test list.
  \end{enumerate}
  1\begin{quote}
  Quote begin.
  \end{quote}
\end{frame}
\end{document}
```

**Comment by louisstuart96** [comment]
The new implementation of `beamercolorbox` seems to have fixed this?
