### ISSUE TITLE
TDS structure is broken

### ISSUE THREAD

**Issue by louisstuart96** [josephwright/beamer#444]
I've updated `beamer` in TeX Live and have found that all the source files are in one folder `texmf/tex/latex/beamer` and so are the doc files. Is this brought by `l3build`?

**Comment by josephwright** [comment]
I'd say 'different', not 'broken'.

From the point of view of `kpsewhich` (and thus any web2c-based TeX system), the location of anything with the correct extensions inside `texmf/tex/latex` will be hashed. Thus even subdivision into packages is just for 'convenience', and further subdivision is really somewhat arbitrary. The only requirement is that `texhash` (`mktexlsr`) is run after any files get moved.

For the development code there can be an argument for dividing stuff up where there are lots of files, which is why I've never messed around with the repo structure. (If starting from scratch there are lots of aspects of `beamer` that might be done differently!)

The change of TDS release structure follows from moving from `make` to using `l3build`. With `make`, the entire `beamer` TDS structure was hard-coded so was always reproduced. In `l3build` the aim is to automate as much as possible, and so files get copied without 'knowing' a target structure. If gets a bit fiddly reproducing the repo structure in the TDS as on Unix `cp` doesn't like copying into non-existence directories. That is fixable if really required, but as I say from the point of view of a TeX run, subdivision in the `texmf` tree isn't required. So at present I've not looked at that.

**Comment by SFr682k** [comment]
From the user's point of view, the old release structure with the `latex` and `doc` files was more clear.

With the files grouped into subdirectories, it was easier to find the licenses and example files mentioned in the documentation.  
Also, `beamer` contains more than 100 `.sty`-files. With the current TDS release structure, which is also the one present at CTAN, it's nearly impossible to find a certain style file using the web interface.

**Comment by ghost** [comment]
@SFr682k The new structure also has advantages. It is now much easier to test different versions, as one can simply put all files in the working directory. Previously one had to move the files individually from each subfolder - otherwise surprising results happened because of a mixture of the version to test and the version installed in the tex distribution.

**Comment by josephwright** [comment]
@SFr682k I can look at this again, but I am mindful that almost all users get their TeX files _via_ their TeX distribution manager. We also now have TDS-style  zips for installation, so I wonder how many users are actually affected. For development work, cloning the Git repo and installing using `l3build` should be reasonably easy.

**Comment by josephwright** [comment]
Of course, if Till had used DocStrip life would have been a lot easier in this regard ...

**Comment by josephwright** [comment]
I'm working on a change to `l3build` to support the _CTAN_ version keeping the structure from the repo. That's not quite the same as the TDS version: I _really_ don't see that the latter needs to be structured. Any comments?

**Comment by SFr682k** [comment]
This seems to be the best solution, since

- the CTAN version is clearly structured and easier browsable and  
- the TDS version containing all style files in the same directory is an advantage for beta testing since one doesn't need to copy them together from different repo directories

**Comment by josephwright** [comment]
@SFr682k For beta testing I'd hope people either use symlinks/multiple local TeX trees or `build.lua install`, but I see the point :) I'll leave the TDS part of the release alone (less work for me).
