### ISSUE TITLE
Wrong slide with \includeslide when slides for title and table of contents are used

### ISSUE THREAD

**Issue by Drachenlaeufer** [josephwright/beamer#452]
When I use \includeslide to include a rendered slide in my article version of the presentation I get a wrong slide. The slide number which is referred to is shifted by the number of slides the title slide and slides for the table of contents need. So, when the title and table of contents is not included in the presentation, then the right slide is included in the article version.
When title and table of contents need say two slides, then the included slide is wrong by two slides.

**Comment by Drachenlaeufer** [comment]
#

**Comment by josephwright** [comment]
Could you construct a small example and add it here?

**Comment by Drachenlaeufer** [comment]
(The packages are just like in my presentation.)


[main.beamer.tex.zip](https://github.com/josephwright/beamer/files/1618534/main.beamer.tex.zip)
[main.article.pdf](https://github.com/josephwright/beamer/files/1618537/main.article.pdf)

**Comment by josephwright** [comment]
Your problem is the line
```latex
\pagenumbering{bychapter}
```
which resets how page numbers are done. So the file `beamer` uses to track pages (the `.snm`)  is wrong and the request for a slide picks up the wrong page.

If you guard that with `\mode`, all is well
```latex
\mode<article>{\pagenumbering{bychapter}}
```
Assuming that fixes for you, I think this will be closed INVALID (_i.e._ not a `beamer` bug).

**Comment by Drachenlaeufer** [comment]
Many thanks! That's it.
