### ISSUE TITLE
Item labels changed appearance with beamer 3.42

### ISSUE THREAD

**Issue by SverreStausland** [josephwright/beamer#453]
I asked a question about this in August 2017: https://tex.stackexchange.com/questions/386878/enumerate-behaves-differently-with-beamer-3-42

I see that this issue has remained in later versions. I assume this is a bug. Any chance of a fix?

**Comment by josephwright** [comment]
I guess I need to look at the theme file (this doesn't show with the vanilla set up).

**Comment by josephwright** [comment]
For reference, the commit involved is 561ebfeca410a68c57179bd8ed1fdb85c9b703d2, in respect of issue #366.

**Comment by josephwright** [comment]
OK, the first thing to note is a change of appearance is expected: the `Rochester` theme is supposed to set square item numbers, and that is what you get without the mini-template argument on the enumerates. The reason that the labels are not 'right' in the boxes is that the size is simply too small. Probably you'll need to adjust the template to suit: I don't think we can change the default size.

I'll track down the indentation issue shortly.

**Comment by josephwright** [comment]
The template adjustment for the labels would look something like
```latex
\setbeamertemplate{enumerate mini template}
{%
  \hbox{%
    \usebeamerfont*{item projected}%
    \usebeamercolor[bg]{item projected}%
    \vrule width3ex height2.2ex depth.8ex%
    \hskip-3ex%
    \hbox to3ex{%
      \hfil%
      \color{fg}\insertenumlabel%
      \hfil}%
  }%
}
```

**Comment by ghost** [comment]
@josephwright About the indentation: could this be the same effect as https://tex.stackexchange.com/a/378012/36296 ? 

With the code from @davidcarlisle:

```
\documentclass{beamer}
\mode<presentation>
    {\usetheme{Rochester}}
    
\setbeamertemplate{enumerate mini template}
{%
  \hbox{%
    \usebeamerfont*{item projected}%
    \usebeamercolor[bg]{item projected}%
    \vrule width3ex height2.2ex depth.8ex%
    \hskip-3ex%
    \hbox to3ex{%
      \hfil%
      \color{fg}\insertenumlabel%
      \hfil}%
  }%
}
    
\makeatletter
\def\beamer@@@enum@[#1]{% partly copied from enumerate.sty
  \@enLab{}\let\@enThe\@enQmark
  \@enloop#1\@enum@
  \ifx\@enThe\@enQmark\@warning{The counter will not be printed.%
    ^^J\space\@spaces\@spaces\@spaces The label is: \the\@enLab}\fi
  \def\insertenumlabel{\the\@enLab}
  \def\beamer@enumtempl{enumerate mini template}%
   \expandafter\let\csname the\@enumctr\endcsname\@enThe
%  \csname c@\@enumctr\endcsname7
%  \expandafter\settowidth
%            \csname leftmargin\romannumeral\@enumdepth\endcsname
%            {\the\@enLab\hspace{\labelsep}}%
  \beamer@enum@}

\makeatother    
    
\begin{document}
\begin{frame}
  \begin{enumerate}[(a)]
    \item Foo
    \item Bar
  \end{enumerate}
  \begin{enumerate}[1]
    \item Foo
    \item Bar
  \end{enumerate}
\end{frame}
\end{document}
```

![document](https://user-images.githubusercontent.com/8226363/34922433-0bace7a6-f990-11e7-9398-7f2d67f19653.png)

**Comment by louisstuart96** [comment]
The `enumerate mini template` has `ball` and `square` styles analogous to the default template for enumerate items, but these two styles may not be set properly to handle the items.

Currently this issue can be fixed by excluding `enumerate mini template` from here:
```
% beamerinnerthemedefault.sty, line 180-181
\defbeamertemplateparent{enumerate items}{enumerate item,enumerate subitem,enumerate subsubitem,enumerate mini template}
{}
```
(So the 'wrong' spelling actually avoided this issue XD)

These two styles for this template need adjustments in the future (or just be dropped?)

**Comment by josephwright** [comment]
@samcarter8 Ah, that explains part of the indent 'fun'. I think we probably want to use the beamer template to work out the width, but there is also an issue that the 'standard' enumerate labels aren't using `enumerate mini template`.

**Comment by josephwright** [comment]
@louisstuart96 I can see what you mean, but that leaves the labels not doing what the style is supposed to do. Perhaps as it's been the case for a long time that is OK, but it feels odd to me. One of the issues we have here is that some design stuff is rather hidden inside templates.

**Comment by josephwright** [comment]
Looking at `beamerbaselocalstructure`, it seems that things are a bit confused here. If one traces through the `enumerate` code, there are two separate templates used:

- If the enumerate labels are not customised we get `enumerate <level>item`
- If the enumerate labels are customised we get `enumerate mini template`

That didn't used to show up 'as designed' as the latter was not set up correctly, so we didn't get the square (or whatever) style of item label at all. What I don't see is what the mini template was _supposed_ to do here: to me the same item/subitem one as normal should apply. I'll try to track it down, either in the Git log or in the docs.

**Comment by josephwright** [comment]
I've looked back over the documentation, and given this a bit of thought, and I think I can see what the concept here is supposed to deal with.

In a 'normal' enumerate situation, the label style is pre-determined and depends on the nesting level. Hence we have item/subitem/subitem label formats with matching `beamer` templates and indent level. Importantly, the style of the label at a given level is always the same. For these cases, the various themes have always worked: square/round/... item labels show up as expected. (Side note: they work provided there are not _too many_ entries: basically the formatting relies on there being fewer than 10.)

In the 'customised' situation, it's no longer possible to be sure of the appearance of a particular entry, hence the existence of a separate `beamer` template here. The idea is then that this `beamer` template should be adjusted to match whatever the customised labels require. There is though still only one `beamer` template here: it's not possible to have different styles of label without adjusting the `beamer` template accordingly.

We only see an issue with some inner themes. In the default one, labels are right-aligned by the `beamer` template, and so changing the width of the label doesn't alter the appearance of the output. However, with the square inner theme the labels are centred in a fixed-width box. Moreover, they are no longer right-aligned so the effect of the width of the label shows up, hence the loss of alignment.

I think we were right to address #366: the inner theme should apply to all item labels, not just those that have not been customised. I don't think there is a code fix to the current issue: the problem is that there are concepts that are not explained. Most obviously, having two different custom labels on the same slide with different widths is an issue. The `beamer` template will likely need to be adjusted for the nature of the labels used: I wonder if we should provide an abstraction for that (some kind of 'mini template item size' setting).

**Comment by josephwright** [comment]
@samcarter8  On the indent business: yes, it's the same issue in the sense the underlying cause is the same. However, I think the problem is as I've said that different label widths _on the same slide_ are not really supported. (I guess one could parse the entire slide, pick up itemizations, work out the maximum width and sort out the alignment, but this is very tricky. Till is pretty clear on the 'keep slides simple' business ...)

**Comment by ghost** [comment]
@josephwright My personal opinion: It would be good enough if all enumerations would be aligned with the standard enumeration. This is also the behaviour of manually setting `\setbeamertemplate{enumerate item}{...}`, not sure why mini templates should be treated differently. There is some additional space to the left to accommodate wider labels without going into the margin and if a label really has to be even wider the `description` environment may be more suitable. 

Right now it looks kind of chaotic (Especially note the different alignment of setting the same layout via `\setbeamertemplate{enumerate item}` and the mini template): 

![screen shot 2018-01-15 at 16 46 50](https://user-images.githubusercontent.com/8226363/34950535-bb17cc5a-fa13-11e7-91da-8fa476a9551a.png)
```

\documentclass{beamer}
\mode<presentation>
    {\usetheme{Rochester}}
    
\setbeamertemplate{enumerate mini template}
{%
  \hbox{%
    \usebeamerfont*{item projected}%
    \usebeamercolor[bg]{item projected}%
    \vrule width3ex height2.2ex depth.8ex%
    \hskip-3ex%
    \hbox to3ex{%
      \hfil%
      \color{fg}\insertenumlabel%
      \hfil}%
  }%
}    
    
\begin{document}
\begin{frame}

	{
	\setbeamertemplate{enumerate item}{%
	  \hbox{%
	    \usebeamerfont*{item projected}%
	    \usebeamercolor[bg]{item projected}%
	    \vrule width3ex height2.2ex depth.8ex%
	    \hskip-3ex%
	    \hbox to3ex{%
	      \hfil%
	      \color{fg}(\alph{enumi})%
	      \hfil}%
	  }%
	}
	\begin{enumerate}
	    \item setbeamertemplate
	\end{enumerate}
	}

  \begin{enumerate}
    \item beamer standard
    \item enumerate
  \end{enumerate}

  \begin{enumerate}[(a)]
    \item mini template
    \item (a)
  \end{enumerate}
  \begin{enumerate}[1]
    \item mini template
    \item 1
  \end{enumerate}
	  
\end{frame}
\end{document}

```

**Comment by josephwright** [comment]
@samcarter8 As I've said, I think the starting point for Till was that on any given slide you'd have only one 'sort' of enumerate. From that point of view there is no expectation that the different types line up. That said, I'm not convinced that
```latex
  \expandafter\settowidth
            \csname leftmargin\romannumeral\@enumdepth\endcsname
            {\the\@enLab\hspace{\labelsep}}%
```
is particularly appropriate either. So I'll drop that part (and close this issue) such that everything aligns using the same width.

**Comment by ghost** [comment]
@josephwright Your decision will make mini templates much easier to use - thank you!
