### ISSUE TITLE
compactitem in beamer broken - \beameritemnestingprefix

### ISSUE THREAD

**Issue by norbusan** [josephwright/beamer#539]
As discussed in https://github.com/josephwright/beamer/issues/435 here a new issue

minimal example
```
\documentclass{beamer}
\listfiles
\usepackage{paralist}
\begin{document}
\begin{frame}
\begin{compactitem}
\item Hello
\item World
\end{compactitem}
\end{frame}
\end{document}
```

Error
```
! Undefined control sequence.
<argument> itemize \beameritemnestingprefix 
                                            item
l.10 \end{frame}
                
? 
```

Log file on my computer attached, TL2019 uptodate
[beamer-bug.log](https://github.com/josephwright/beamer/files/3436451/beamer-bug.log)

**Comment by louisstuart96** [comment]
`beamer` adds a patch file for `paralist` so that one could use enhanced list environments together with `beamer`'s style designed for list environments. For now it only patches `enumerate` and `itemize` environments, but this patch file may influnece other environments. We will try to update this patch file in the future.

Try this temporary code before the `compactitem` environment. If it causes any further problem, please contact us:
```
\let\beameritemnestingprefix\empty
```

**Comment by louisstuart96** [comment]
Commit a538e9f has patched these two environments. You can even use them together with `beamer`'s overlays:
```
% overlays are specified first, like the usage of `enumerate` in beamer
\begin{compactenum}[<+->][$a$] 
  \item Hello
  \item world
\end{compactenum}
```

The documentation will be updated soon.

**Comment by norbusan** [comment]
Great, thanks a lot!
