### ISSUE TITLE
Add 18:8 and 18:9 aspect ratios

### ISSUE THREAD

**Issue by XVilka** [josephwright/beamer#549]
There are some huge presentation screens that use this aspect ratio (and it became kind of popular in China for some reason), while 18:9 is popular among smartphones.

**Comment by louisstuart96** [comment]
@samcarter Perhaps the best idea is to let users define their own scales and aspect ratios, what do you think?

**Comment by josephwright** [comment]
Yeah, we do seem to get a steady stream of these requests.

**Comment by samcarter** [comment]
@louisstuart96 I've been thinking about this problem for quite some time and could imagine 2 approaches (not necessarily exclusive)

- Expend the `aspectration` option. If an unknown value is passed to this option, the default value is kept for the paperheight and the paperwidth is calculated to match the ratio. This is my preferred approach.

- make it easier for the user to change the paper size by adding a documentclass option that passes values to the geometry package like it is done for xcolor, e.g. `\documentclass[geometry={paperwidth=20cm}]{beamer}` (I know that this is not strictly necessary, because the user could use `\geometry{...}` in the preamble, but it might make usage easier). This has the disadvantage that the user needs to know\look up the approximate default size and calculate the values themselves. This could be combined with option 1 to give the user as much possibilities as possible

**Comment by louisstuart96** [comment]
@samcarter The first approach changes the way of parsing the `aspectratio` option, so that the old options may be incompatible. The second one exposes too much options to users: Someone might try `left=...`, `hmargin=...` or `headheight=...`, which have risks of breaking the layout of themes.

**Comment by samcarter** [comment]
@louisstuart96 To keep the already existing options compatible I would only calculate the aspect ratio for unknown values passed to the option. For example `54` would still use 12.50 cm and 10.00 cm, but 188 would calculate the necessary values.
