### ISSUE TITLE
Loading package beamerarticle under article class clobbers the default paper size in favour of US letter

### ISSUE THREAD

**Issue by krivit** [josephwright/beamer#551]
# Steps to reproduce
1. Configure the system to default to A4 paper size (e.g., via `/etc/paper`).
2. Confirm that the system defaults to A4 paper size by generating the document from a file along the lines of
    ```
    \documentclass{article}
    \usepackage{lipsum}
    \begin{document}
    \lipsum[1]
    \end{document}
    ```
    using `pdflatex`.
3. Generate a document from a file along the lines of
    ```
    \documentclass{article}
    \usepackage{beamerarticle}
    \usepackage{lipsum}
    \begin{document}
    \lipsum[1]
    \end{document}
    ```
    using `pdflatex`.

## Expected result
Both files generate virtually identical A4-sized PDF files.

## Actual result
Step 2 generates an A4-sized PDF file, whereas Step 3 generates a US Letter-sized PDF file.

# Other notes
## Workaround
It appears that setting paper size explicitly, i.e.,
```
\documentclass[a4paper]{article}
\usepackage{beamerarticle}
\usepackage{lipsum}
\begin{document}
\lipsum[1]
\end{document}
```
produces an A4-sized document.

## Relevant system information
Debian Linux, with `texlive-latex-recommended` version `2019.20190930-1` and Beamer `v3.56`. Please let me know if any other information would help.

# Attachements
The three example LaTeX files and the PDFs they produce can be found in
[test.zip](https://github.com/josephwright/beamer/files/3689585/test.zip).

**Comment by davidcarlisle** [comment]
Your first, article class document is incorrect. LaTeX always defaults to US-letter, so without `[a4paper]` that is set with a text block and margins designed for US Letter, but with a PDF media size with your system default of A4. The fact that it looks sort of reasonable is just because the sizes are not that different.

If you load any package that allows you to specify back end driver code (graphics, color, geometry, hyperref for example) then latex will specify the media size to match the typeset document and your article class pdf will specify USletter.

Beamer of course includes color/graphics by default so sees the expected behaviour that the PDF media size matches the intended typeset layout.

**Comment by krivit** [comment]
Thanks for the quick analysis. It seems like a Debian issue, then?

**Comment by davidcarlisle** [comment]
No it is (unfortunately) user error, you should specify the page size explicitly.

**Comment by samcarter** [comment]
A simple example to see that @davidcarlisle's analysis is correct (what else could it be :) 

```
\documentclass{article}
\usepackage{lipsum}

\usepackage[
%	noxcolor % try with and without this option
]{beamerarticle}

\begin{document}
\lipsum[1]

\the\pdfpageheight
\end{document}
```

**Comment by krivit** [comment]
Thanks for explaining!
