### ISSUE TITLE
Frame with fragile option in argument of \mode<⟨mode spec.⟩> gives error

### ISSUE THREAD

**Issue by dbitouze** [josephwright/beamer#558]
(Maybe related to #543). The following MCE:
```latex
\documentclass{beamer}
\begin{document}
\mode<beamer>{
  \begin{frame}[fragile]
    Foo.
  \end{frame}
}
\end{document}
```
 doesn't compile (`beamer` 2019/09/29 v3.57), with error:
```
! Extra }, or forgotten \endgroup.
\endframe ->\egroup 
                    \begingroup \def \@currenvir {frame}
l.1 Foo. \end {frame}
                      \beamer@mode \par
```
I'm pretty sure it used to compile like a charm.

**Comment by samcarter** [comment]
Would 

```
\documentclass{beamer}
\begin{document}

\begin{frame}<beamer>[fragile]
    Foo.
\end{frame}

\end{document}
```

be a workaround?

**Comment by dbitouze** [comment]
@samcarter Yes, indeed: thanks :) I opened this issue to point out a broken behavior.

**Edit:** The only drawback of this workaround is in case of a significant number of frames have to be taken in account only in a `⟨given mode⟩`. Okay, another option would be to proceed as follows:
```latex
\mode
<⟨given mode⟩>

\begin{frame}[fragile]
    ...
\end{frame}
...
\begin{frame}[fragile]
    ...
\end{frame}

\mode
<all>
```

**Comment by louisstuart96** [comment]
The most possibly related change would be df2942e ; I'm not sure for now.

In your MCE, something breaks the line parsing process, so `.vrb` is not written line-by-line.
It takes time to check what is wrong.

EDIT: The `\mode` command reads the entire frame as its parameter, and the tokens are transformed in this process (line ends to space tokens, empty lines to `\par`, etc.), making them look like:
```
\documentclass{beamer}
\begin{document}
  \begin{frame}[fragile] Foo. \end{frame}
\end{document}
```
Then the line parsing process goes wrong.

I wonder why it used to compile correctly, because the behavior of `\mode` command has not altered for very long.

**Comment by dbitouze** [comment]
> I wonder why it used to compile correctly, because the behavior of `\mode` command has not altered for very long.

Some of my old documents, that used to compile like a charm, suddenly don't compile because of this error.

**Comment by louisstuart96** [comment]
> Some of my old documents, that used to compile like a charm, suddenly don't compile because of this error.

Could you provide more information about your old documents, like `beamer` version or compilation log?

**Comment by dbitouze** [comment]
Well, I cannot tell when they started to fail to compile, since I didn't use them for few months. I guess they compiled nicely in last June (and I noticed two new release since then: 3.56 2019-07-23 and 3.57 2019-09-29).

**Comment by louisstuart96** [comment]
I have just tested your MCE with `beamer v3.38` published on 2017-01-01, and the result is failure.

If your documents were not older than that time, then I'm afraid your MCE cannot reproduce the actual problems in these documents, because the relative macros in `beamer` have not changed since then.

**Comment by dbitouze** [comment]
Even with `git bisect`, I can't find a previous version of `beamer` that makes my old documents compile as previously: probably a third party package is involved.

Sorry for the noise.
