### ISSUE TITLE
Documentation about `\newenvironment`: tweaks needed?

### ISSUE THREAD

**Issue by dbitouze** [josephwright/beamer#827]
Does the following MCE, build from the current (3.68) documentation (page 86), give the expected result? 
```latex
\documentclass{beamer}
\newenvironment<>{myboldblock}[1]{%
  \begin{actionenv}#2%
    \textbf{#1}
    \par}
  {\par%
  \end{actionenv}}
\begin{document}
\begin{frame}
  \begin{myboldblock}<2>
    This theorem is shown only on the second slide.
  \end{myboldblock}
\end{frame}
\end{document}
```
Indeed, the second slide looks like:

![image](https://user-images.githubusercontent.com/1032633/216952637-3ac24272-2f63-4859-aa4f-e0825a3d6a7f.png)

On the same page, it is written “_Example:_ Text in the following environment is normally bold and _italic_ on non-specified slides:” but I guess there's no _italic_ in the involved examples:
```latex
\newenvironment<>{boldornormal}
{\begin{altenv}#1
{\begin{bfseries}}{\end{bfseries}}
{}{}}
{\end{altenv}}
``` 
and:
```latex
\newenvironment{boldornormal}
{\begin{altenv}
{\begin{bfseries}}{\end{bfseries}}
{}{}}
{\end{altenv}}
```
BTW, wouldn't be more advised to use `bfseries` as a _declaration_ instead of an _environment_, e.g.:
```latex
\newenvironment<>{boldornormal}
{\begin{altenv}#1
    {\bfseries}{}
    {}{}}
  {\end{altenv}}
```

**Comment by samcarter** [comment]
@dbitouze  Thanks for the report! I added the missing title for the theorem and fixed the wording for the `boldenormal` environment.

@josephwright I left the `\begin{bfseries}...\end{bfseries}` in the example for now because I think it makes it easier to see where the environment starts and ends. What do you think? Should it be changed to something else? Using the `center` environment all the time would be a bit boring...
